// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCekY6h9zSiOC6062KiVWBTQmvMQILsD1k',
    appId: '1:1006396391721:web:b987649ba259b718a9f738',
    messagingSenderId: '1006396391721',
    projectId: 'map-lab-utc2-e-commerce-64591',
    authDomain: 'map-lab-utc2-e-commerce-64591.firebaseapp.com',
    storageBucket: 'map-lab-utc2-e-commerce-64591.firebasestorage.app',
    measurementId: 'G-N929NY235K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUxXpdMLdlkiNoq4CWB1hfj7ok0ioioGc',
    appId: '1:1006396391721:android:737add63d313fdb5a9f738',
    messagingSenderId: '1006396391721',
    projectId: 'map-lab-utc2-e-commerce-64591',
    storageBucket: 'map-lab-utc2-e-commerce-64591.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCekY6h9zSiOC6062KiVWBTQmvMQILsD1k',
    appId: '1:1006396391721:web:e56871ef18a3db15a9f738',
    messagingSenderId: '1006396391721',
    projectId: 'map-lab-utc2-e-commerce-64591',
    authDomain: 'map-lab-utc2-e-commerce-64591.firebaseapp.com',
    storageBucket: 'map-lab-utc2-e-commerce-64591.firebasestorage.app',
    measurementId: 'G-NCCCQPBLJH',
  );
}
