abstract class AppRoutes {
  AppRoutes._();

  static const splash = '/';
  static const onboarding = '/onboarding';
  static const login = '/login';
  static const register = '/register';
  static const verifyEmail = '/verify-email';
  static const registerSuccess = '/register-success';
  static const forgetPassword = '/forget-password';
  static const resetEmailSent = '/reset-email-sent';
  static const mainNavigation = '/main-navigation';
  static const home = '/home';
  static const myStore = '/mystore';
  static const productDetail = '/product-detail';
  static const cart = '/cart';
  static const cartOverview = '/cart-overview';
  static const shippingAddress = '/shipping-address';
  static const orderConfirmation = '/order-confirmation';
  static const orderReview = '/order-review';
  static const orderSuccess = '/order-success';
  static const myOrders = '/my-orders';
  static const popularProduct = '/popular-product';
  static const allBrands = '/all-brand';
  static const brandDetail = '/brand-detail';
  static const profile = '/profile';
  static const updateAccount = '/update-account';
  static const changeName = '/change-name';
  static const changeUsername = '/change-username';
  static const changePassword = '/change-password';
  static const changeEmail = '/change-email';
  static const changePhoneNumber = '/change-phonenumber';
  static const changeGender = '/change-gender';
  static const changeDateofBirth = '/change-datebirth';
  static const myShippingAddressview = '/my-shipping-address';
  static const myBankAccountview = '/my-bank-account';
  static const settings = '/settings';
  static const wishlist = '/wishlist';
  static const writeReview = '/write-review';
  static const reviewRating = '/review-rating';
  static const notifications = '/notifications';
  static const orderDetail = '/order-detail';
}
